### ISSUE TITLE
WinJump question & issue please

### ISSUE THREAD

**Issue by ComputerCulture** [widavies/WinJump#32] opened 2023-10-14 00:19 UTC
Hello,

Enjoying this software, and thank you. 

1. Could you please show how to add (Shortcut Keys as an example to the standard .winjump File to, 
"Move applications to a specific desktop with a shortcut" ?

2. I noticed when when exit the program via the menu, the screen goes black for a few seconds, all the taskbar icons and the system tray icons disappear. Then they all reload.  If using task manager  to close the program and end the process, the above issue does not occur.

OS Windows 10 inside VMware workstation.

Thank you

Kind regards
CC

**Comment by widavies** [comment] 2023-10-14 05:10
@ComputerCulture Appreciate it, glad it's useful.

1. Within the [Example](https://github.com/widavies/WinJump#example) section of the README, there's an example configuration file that has the following section:
```json
  "move-window-to-desktop": {
    "shortcut": "alt+shift"
  },
```

This sets the move-to-desktop short cut, in this case (the default), pressing "alt+shift" plus a number will move your currently focused application to desktop N (whatever number key you pressed). You could switch this to "win+shift" for example if you want a different shortcut. Let me know if this actually works, I've noticed it could be a bit buggy.

2. This is actually normal behavior. It's not strictly necessary but the reasoning is this:
- The `explorer.exe` process handles a variety of functionality on Windows - it's not just for a file explorer window, but it also runs the taskbar, start menu, etc. By default, `explorer.exe` will register the `win+N` shortcut that will open the N'th application on your taskbar. If you're using a `win+N` shortcut in WinJump, it needs to kill `explorer.exe` so it can register the shortcut, then relaunch it. In order to exit WinJump, I have to restart `explorer.exe` so that these built in shortcuts are properly re-registered by the system. This restart is normal, but the reason why your taskbar will disappear and re-appear. If you're not using the Windows key in any of your shortcuts, this shouldn't be necessary. I think I forgot to add a check for this in the `Exit` action, so I'll add it so it behaves better. Thanks for the advice.

Will

**Comment by ComputerCulture** [comment] 2023-10-14 07:01
@widavies  Hi Will, thank you for your reply.

Not sure if i am doing this correct. Say i want to move a focused window to another virtual desktop. i am  using alt+shift+2 
The window does not move and stays on 1
In the the config file as below.  i am doing this correct?  Thank you Will 

"move-window-to-desktop": {
    "shortcut": "alt+shift"
  },

**Comment by ComputerCulture** [comment] 2023-10-20 05:06
@widavies Hi Will,

Just an update, thought i would change shortcut 
move-window-to-desktop
using  win+shift
This did not work either, and also the program would not even load. Just got black screen then explorer.exe reloads.

Thank you Will, Looking forward to future releases.

Kind regards
CC

**Comment by dozn** [comment] 2023-12-01 21:04
I can confirm that the move-window-to-desktop feature doesn't seem to work.

**Comment by widavies** [comment] 2023-12-01 21:21
Thanks, should have a release out before too long. Been a very busy fall for me.

**Comment by widavies** [comment] 2024-01-04 17:39
@ComputerCulture Go ahead and try the latest pre-release [here](https://github.com/widavies/WinJump/releases/tag/2.0.9). It fixes 1. somewhat, explorer still needs to be restarted if you used any `win+` modifiers, but I now skip restarting it if you only use `alt+` modifiers (the default).

Moving windows between desktops should work. Make sure your config file looks like this:

```
{
  "toggle-groups": [],
  "jump-current-goes-to-last": false,
  "change-desktops-with-scroll": true,
  "move-window-to-desktop": {
      "shortcut": "alt+shift" 
  },
  "jump-to": [
    {
      "Shortcut": "win+d0",
      "desktop": 10
    },
    {
      "Shortcut": "win+d1",
      "desktop": 1
    },
    {
      "Shortcut": "win+d2",
      "desktop": 2
    },
    {
      "Shortcut": "win+d3",
      "desktop": 3
    },
    {
      "Shortcut": "win+d4",
      "desktop": 4
    },
    {
      "Shortcut": "win+d5",
      "desktop": 5
    },
    {
      "Shortcut": "win+d6",
      "desktop": 6
    },
    {
      "Shortcut": "win+d7",
      "desktop": 7
    },
    {
      "Shortcut": "win+d8",
      "desktop": 8
    },
    {
      "Shortcut": "win+d9",
      "desktop": 9
    }
  ]
}
```

(Make sure to reload the config by right clicking WinJump and selecting *Reload config*

Try opening a window on Desktop 1, then make sure you have another virtual desktop open (there have to be at least two for it to work, my shortcut won't create a new desktop automatically). Then, press `alt+shift+2` and `alt+shift+1` and you should see the window move back and forth.

Let me know if this release fixes the problems and I'll close the issue.

**Comment by NicoVogel** [comment] 2024-01-05 19:03
> I can confirm that the `move-window-to-desktop` feature doesn't seem to work on Windows 11.

Same for me.

@widavies I tried the prerelease `2.0.9` with windows 11 (23H2, 22631.2861) and it works now just fine with `alt` and `win`.

**Comment by widavies** [comment] 2024-01-05 23:50
> > I can confirm that the `move-window-to-desktop` feature doesn't seem to work on Windows 11.
> 
> Same for me.
> 
> @widavies I tried the prerelease `2.0.9` with windows 11 (23H2, 22631.2861) and it works now just fine with `alt` and `win`.

Great! Thanks for testing it out for me.

**Closed** 2024-01-05 23:50 UTC
